[Icon Theme]
Name=Sweet-Purple-Filled
Comment=Purple folders for Sweet theme.
Inherits=candy-icons,breeze-dark,gnome,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor


# Directory list
Directories=Places/48,Places/16
Example=folder
DisplayDepth=32

FollowsColorScheme=true

[Places/48]
Size=48
Context=Places
MinSize=32
MaxSize=512
Type=Scalable

[Places/16]
Size=16
Context=Places
MinSize=8
MaxSize=32
Type=Scalable
